name: Django CI (SQLite)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip3 install --upgrade pip
          pip3 install -r messaging_app/requirements.txt

      - name: Run Django migrations
        run: |
          source venv/bin/activate
          cd messaging_app
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          source venv/bin/activate
          cd messaging_app
          python manage.py test
